################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../DOOM/am_map.c \
../DOOM/d_event.c \
../DOOM/d_items.c \
../DOOM/d_iwad.c \
../DOOM/d_loop.c \
../DOOM/d_main.c \
../DOOM/d_mode.c \
../DOOM/d_net.c \
../DOOM/doomdef.c \
../DOOM/doomgeneric.c \
../DOOM/doomgeneric_stm32discovery.c \
../DOOM/doomstat.c \
../DOOM/dstrings.c \
../DOOM/dummy.c \
../DOOM/f_finale.c \
../DOOM/f_wipe.c \
../DOOM/g_game.c \
../DOOM/gusconf.c \
../DOOM/hu_lib.c \
../DOOM/hu_stuff.c \
../DOOM/i_cdmus.c \
../DOOM/i_endoom.c \
../DOOM/i_input.c \
../DOOM/i_joystick.c \
../DOOM/i_main.c \
../DOOM/i_scale.c \
../DOOM/i_sound.c \
../DOOM/i_system.c \
../DOOM/i_timer.c \
../DOOM/i_video.c \
../DOOM/icon.c \
../DOOM/info.c \
../DOOM/m_argv.c \
../DOOM/m_bbox.c \
../DOOM/m_cheat.c \
../DOOM/m_config.c \
../DOOM/m_controls.c \
../DOOM/m_fixed.c \
../DOOM/m_menu.c \
../DOOM/m_misc.c \
../DOOM/m_random.c \
../DOOM/memio.c \
../DOOM/p_ceilng.c \
../DOOM/p_doors.c \
../DOOM/p_enemy.c \
../DOOM/p_floor.c \
../DOOM/p_inter.c \
../DOOM/p_lights.c \
../DOOM/p_map.c \
../DOOM/p_maputl.c \
../DOOM/p_mobj.c \
../DOOM/p_plats.c \
../DOOM/p_pspr.c \
../DOOM/p_saveg.c \
../DOOM/p_setup.c \
../DOOM/p_sight.c \
../DOOM/p_spec.c \
../DOOM/p_switch.c \
../DOOM/p_telept.c \
../DOOM/p_tick.c \
../DOOM/p_user.c \
../DOOM/r_bsp.c \
../DOOM/r_data.c \
../DOOM/r_draw.c \
../DOOM/r_main.c \
../DOOM/r_plane.c \
../DOOM/r_segs.c \
../DOOM/r_sky.c \
../DOOM/r_things.c \
../DOOM/s_sound.c \
../DOOM/sha1.c \
../DOOM/sounds.c \
../DOOM/st_lib.c \
../DOOM/st_stuff.c \
../DOOM/statdump.c \
../DOOM/tables.c \
../DOOM/v_video.c \
../DOOM/w_checksum.c \
../DOOM/w_file.c \
../DOOM/w_file_stdc.c \
../DOOM/w_main.c \
../DOOM/w_wad.c \
../DOOM/wi_stuff.c \
../DOOM/z_zone.c 

OBJS += \
./DOOM/am_map.o \
./DOOM/d_event.o \
./DOOM/d_items.o \
./DOOM/d_iwad.o \
./DOOM/d_loop.o \
./DOOM/d_main.o \
./DOOM/d_mode.o \
./DOOM/d_net.o \
./DOOM/doomdef.o \
./DOOM/doomgeneric.o \
./DOOM/doomgeneric_stm32discovery.o \
./DOOM/doomstat.o \
./DOOM/dstrings.o \
./DOOM/dummy.o \
./DOOM/f_finale.o \
./DOOM/f_wipe.o \
./DOOM/g_game.o \
./DOOM/gusconf.o \
./DOOM/hu_lib.o \
./DOOM/hu_stuff.o \
./DOOM/i_cdmus.o \
./DOOM/i_endoom.o \
./DOOM/i_input.o \
./DOOM/i_joystick.o \
./DOOM/i_main.o \
./DOOM/i_scale.o \
./DOOM/i_sound.o \
./DOOM/i_system.o \
./DOOM/i_timer.o \
./DOOM/i_video.o \
./DOOM/icon.o \
./DOOM/info.o \
./DOOM/m_argv.o \
./DOOM/m_bbox.o \
./DOOM/m_cheat.o \
./DOOM/m_config.o \
./DOOM/m_controls.o \
./DOOM/m_fixed.o \
./DOOM/m_menu.o \
./DOOM/m_misc.o \
./DOOM/m_random.o \
./DOOM/memio.o \
./DOOM/p_ceilng.o \
./DOOM/p_doors.o \
./DOOM/p_enemy.o \
./DOOM/p_floor.o \
./DOOM/p_inter.o \
./DOOM/p_lights.o \
./DOOM/p_map.o \
./DOOM/p_maputl.o \
./DOOM/p_mobj.o \
./DOOM/p_plats.o \
./DOOM/p_pspr.o \
./DOOM/p_saveg.o \
./DOOM/p_setup.o \
./DOOM/p_sight.o \
./DOOM/p_spec.o \
./DOOM/p_switch.o \
./DOOM/p_telept.o \
./DOOM/p_tick.o \
./DOOM/p_user.o \
./DOOM/r_bsp.o \
./DOOM/r_data.o \
./DOOM/r_draw.o \
./DOOM/r_main.o \
./DOOM/r_plane.o \
./DOOM/r_segs.o \
./DOOM/r_sky.o \
./DOOM/r_things.o \
./DOOM/s_sound.o \
./DOOM/sha1.o \
./DOOM/sounds.o \
./DOOM/st_lib.o \
./DOOM/st_stuff.o \
./DOOM/statdump.o \
./DOOM/tables.o \
./DOOM/v_video.o \
./DOOM/w_checksum.o \
./DOOM/w_file.o \
./DOOM/w_file_stdc.o \
./DOOM/w_main.o \
./DOOM/w_wad.o \
./DOOM/wi_stuff.o \
./DOOM/z_zone.o 

C_DEPS += \
./DOOM/am_map.d \
./DOOM/d_event.d \
./DOOM/d_items.d \
./DOOM/d_iwad.d \
./DOOM/d_loop.d \
./DOOM/d_main.d \
./DOOM/d_mode.d \
./DOOM/d_net.d \
./DOOM/doomdef.d \
./DOOM/doomgeneric.d \
./DOOM/doomgeneric_stm32discovery.d \
./DOOM/doomstat.d \
./DOOM/dstrings.d \
./DOOM/dummy.d \
./DOOM/f_finale.d \
./DOOM/f_wipe.d \
./DOOM/g_game.d \
./DOOM/gusconf.d \
./DOOM/hu_lib.d \
./DOOM/hu_stuff.d \
./DOOM/i_cdmus.d \
./DOOM/i_endoom.d \
./DOOM/i_input.d \
./DOOM/i_joystick.d \
./DOOM/i_main.d \
./DOOM/i_scale.d \
./DOOM/i_sound.d \
./DOOM/i_system.d \
./DOOM/i_timer.d \
./DOOM/i_video.d \
./DOOM/icon.d \
./DOOM/info.d \
./DOOM/m_argv.d \
./DOOM/m_bbox.d \
./DOOM/m_cheat.d \
./DOOM/m_config.d \
./DOOM/m_controls.d \
./DOOM/m_fixed.d \
./DOOM/m_menu.d \
./DOOM/m_misc.d \
./DOOM/m_random.d \
./DOOM/memio.d \
./DOOM/p_ceilng.d \
./DOOM/p_doors.d \
./DOOM/p_enemy.d \
./DOOM/p_floor.d \
./DOOM/p_inter.d \
./DOOM/p_lights.d \
./DOOM/p_map.d \
./DOOM/p_maputl.d \
./DOOM/p_mobj.d \
./DOOM/p_plats.d \
./DOOM/p_pspr.d \
./DOOM/p_saveg.d \
./DOOM/p_setup.d \
./DOOM/p_sight.d \
./DOOM/p_spec.d \
./DOOM/p_switch.d \
./DOOM/p_telept.d \
./DOOM/p_tick.d \
./DOOM/p_user.d \
./DOOM/r_bsp.d \
./DOOM/r_data.d \
./DOOM/r_draw.d \
./DOOM/r_main.d \
./DOOM/r_plane.d \
./DOOM/r_segs.d \
./DOOM/r_sky.d \
./DOOM/r_things.d \
./DOOM/s_sound.d \
./DOOM/sha1.d \
./DOOM/sounds.d \
./DOOM/st_lib.d \
./DOOM/st_stuff.d \
./DOOM/statdump.d \
./DOOM/tables.d \
./DOOM/v_video.d \
./DOOM/w_checksum.d \
./DOOM/w_file.d \
./DOOM/w_file_stdc.d \
./DOOM/w_main.d \
./DOOM/w_wad.d \
./DOOM/wi_stuff.d \
./DOOM/z_zone.d 


# Each subdirectory must supply rules for building sources it contributes
DOOM/%.o: ../DOOM/%.c DOOM/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F429xx -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../FATFS/Target -I../FATFS/App -I../USB_HOST/App -I../USB_HOST/Target -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I"C:/Users/Branislav/STM32CubeIDE/new/idk/DOOM/include" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

